name: cherrilog
description: Perhaps the simplest and most useful log library for dart. Lightweight and easy to apply.
version: 0.2.1
repository: https://github.com/AndromedaX7/cherrilog
publish_to: http://192.168.1.96
homepage: https://pub.local

environment:
  sdk: ^3.1.0

dependencies:
  dart_art: ^0.1.0+1
  intl: ^0.19.0
  stack_trace: ^1.11.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - logging
  - logger
  - log
  - utility
