name: Publish to pub.dev

on:
  push:
    branches:
      - main
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v{{version}}'


jobs:
  publish:
    name: 'Publish to pub.dev'
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK with JWT token
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Test packages
        run: flutter test

      - name: Publish - dry run
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish -f
